# Este workflow realiza el build de la aplicación y corre todos los tests.

name: Build and Test

on:
  push:
    branches: [master, release]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
